/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
export interface SignupInput {
  email: string;
  password: string;
  firstname: string;
  lastname: string;
}

export interface Auth {
  accessToken: string;
  refreshToken: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface RefreshTokenInput {
  token: string;
}

export interface RefreshResponceModel {
  access_token: string;
}

export interface CreatePostInput {
  content: string;
  title: string;
}

export type PostResponceContent = { [key: string]: unknown };

export type PostResponceAuthor = { [key: string]: unknown };

export interface PostResponce {
  title: string;
  content: PostResponceContent;
  published: boolean;
  author: PostResponceAuthor;
}

export interface PostResponse {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string;
  content: string;
  published: boolean;
  authorId: string;
}
