/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type { Auth, LoginInput, RefreshResponceModel, RefreshTokenInput, SignupInput } from '../index.schemas';
import { customInstance } from '../../mutators/fetch-instance';

/**
 * @summary Signup a new user
 */
export type signUpResponse = {
  data: Auth;
  status: number;
  headers: Headers;
};

export const getSignUpUrl = () => {
  return `/auth/signup`;
};

export const signUp = async (signupInput: SignupInput, options?: RequestInit): Promise<signUpResponse> => {
  return customInstance<signUpResponse>(getSignUpUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signupInput),
  });
};

/**
 * @summary Login an existing user
 */
export type signInResponse = {
  data: Auth;
  status: number;
  headers: Headers;
};

export const getSignInUrl = () => {
  return `/auth/login`;
};

export const signIn = async (loginInput: LoginInput, options?: RequestInit): Promise<signInResponse> => {
  return customInstance<signInResponse>(getSignInUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginInput),
  });
};

/**
 * @summary Refresh access token using a refresh token
 */
export type refreshTokenResponse = {
  data: RefreshResponceModel;
  status: number;
  headers: Headers;
};

export const getRefreshTokenUrl = () => {
  return `/auth/refresh-token`;
};

export const refreshToken = async (refreshTokenInput: RefreshTokenInput, options?: RequestInit): Promise<refreshTokenResponse> => {
  return customInstance<refreshTokenResponse>(getRefreshTokenUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenInput),
  });
};
