/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';
import {
  HttpResponse, delay, http 
} from 'msw';
import type {
  Auth, RefreshResponceModel 
} from '../index.schemas';

export const getSignUpResponseMock = (overrideResponse: Partial<Auth> = {}): Auth => ({
  accessToken: faker.string.alpha(20),
  refreshToken: faker.string.alpha(20),
  ...overrideResponse,
});

export const getSignUpResponseMock201 = (overrideResponse: Partial<Auth> = {}): Auth => ({
  accessToken: faker.string.alpha(20),
  refreshToken: faker.string.alpha(20),
  ...overrideResponse,
});

export const getSignInResponseMock = (overrideResponse: Partial<Auth> = {}): Auth => ({
  accessToken: faker.string.alpha(20),
  refreshToken: faker.string.alpha(20),
  ...overrideResponse,
});

export const getSignInResponseMock200 = (overrideResponse: Partial<Auth> = {}): Auth => ({
  accessToken: faker.string.alpha(20),
  refreshToken: faker.string.alpha(20),
  ...overrideResponse,
});

export const getRefreshTokenResponseMock = (overrideResponse: Partial<RefreshResponceModel> = {}): RefreshResponceModel => ({
  access_token: faker.string.alpha(20),
  ...overrideResponse,
});

export const getRefreshTokenResponseMock200 = (overrideResponse: Partial<RefreshResponceModel> = {}): RefreshResponceModel => ({
  access_token: faker.string.alpha(20),
  ...overrideResponse,
});

export const getSignUpMockHandler = (overrideResponse?: Auth | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Auth> | Auth)) => {
  return http.post('*/auth/signup', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined ? (typeof overrideResponse === 'function' ? await overrideResponse(info) : overrideResponse) : getSignUpResponseMock(),
      ),
      { status: 201, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSignUpMockHandler201 = (overrideResponse?: Auth | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Auth> | Auth)) => {
  return http.post('*/auth/signup', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSignUpResponseMock201(),
      ),
      { status: 201, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSignInMockHandler = (overrideResponse?: Auth | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Auth> | Auth)) => {
  return http.post('*/auth/login', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined ? (typeof overrideResponse === 'function' ? await overrideResponse(info) : overrideResponse) : getSignInResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getSignInMockHandler200 = (overrideResponse?: Auth | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Auth> | Auth)) => {
  return http.post('*/auth/login', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSignInResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getRefreshTokenMockHandler = (
  overrideResponse?: RefreshResponceModel | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RefreshResponceModel> | RefreshResponceModel),
) => {
  return http.post('*/auth/refresh-token', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getRefreshTokenResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getRefreshTokenMockHandler200 = (
  overrideResponse?: RefreshResponceModel | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RefreshResponceModel> | RefreshResponceModel),
) => {
  return http.post('*/auth/refresh-token', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getRefreshTokenResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getAuthMock = () => [getSignUpMockHandler(), getSignInMockHandler(), getRefreshTokenMockHandler()];
