/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type {
  Auth, LoginInput, RefreshResponceModel, RefreshTokenInput, SignupInput 
} from '../index.schemas';
import { getBaseUrlBasedOnServer } from '@/utils/functions';

/**
 * @summary Signup a new user
 */
export type signUpResponse = {
  data: Auth;
  status: number;
  headers: Headers;
};

export const getSignUpUrl = () => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/auth/signup`;
};

export const signUp = async (signupInput: SignupInput, options?: RequestInit): Promise<signUpResponse> => {
  const res = await fetch(getSignUpUrl(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signupInput),
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: signUpResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as signUpResponse;
};

/**
 * @summary Login an existing user
 */
export type signInResponse = {
  data: Auth;
  status: number;
  headers: Headers;
};

export const getSignInUrl = () => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/auth/login`;
};

export const signIn = async (loginInput: LoginInput, options?: RequestInit): Promise<signInResponse> => {
  const res = await fetch(getSignInUrl(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginInput),
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: signInResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as signInResponse;
};

/**
 * @summary Refresh access token using a refresh token
 */
export type refreshTokenResponse = {
  data: RefreshResponceModel;
  status: number;
  headers: Headers;
};

export const getRefreshTokenUrl = () => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/auth/refresh-token`;
};

export const refreshToken = async (refreshTokenInput: RefreshTokenInput, options?: RequestInit): Promise<refreshTokenResponse> => {
  const res = await fetch(getRefreshTokenUrl(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenInput),
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: refreshTokenResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as refreshTokenResponse;
};
