/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';
import {
  HttpResponse, delay, http 
} from 'msw';
import type {
  PostResponce, PostResponse 
} from '../index.schemas';

export const getCreatePostResponseMock = (overrideResponse: Partial<PostResponce> = {}): PostResponce => ({
  title: faker.string.alpha(20),
  content: {},
  published: faker.datatype.boolean(),
  author: {},
  ...overrideResponse,
});

export const getCreatePostResponseMock200 = (overrideResponse: Partial<PostResponce> = {}): PostResponce => ({
  title: faker.string.alpha(20),
  content: {},
  published: faker.datatype.boolean(),
  author: {},
  ...overrideResponse,
});

export const getGetPostsResponseMock = (): PostResponse[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.alpha(20),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    title: faker.string.alpha(20),
    content: faker.string.alpha(20),
    published: faker.datatype.boolean(),
    authorId: faker.string.alpha(20),
  }));

export const getGetPostsResponseMock200 = (): PostResponse[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.alpha(20),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    title: faker.string.alpha(20),
    content: faker.string.alpha(20),
    published: faker.datatype.boolean(),
    authorId: faker.string.alpha(20),
  }));

export const getGetUserPostsResponseMock = (): PostResponse[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.alpha(20),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    title: faker.string.alpha(20),
    content: faker.string.alpha(20),
    published: faker.datatype.boolean(),
    authorId: faker.string.alpha(20),
  }));

export const getGetUserPostsResponseMock200 = (): PostResponse[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.alpha(20),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    title: faker.string.alpha(20),
    content: faker.string.alpha(20),
    published: faker.datatype.boolean(),
    authorId: faker.string.alpha(20),
  }));

export const getGetPostResponseMock = (overrideResponse: Partial<PostResponse> = {}): PostResponse => ({
  id: faker.string.alpha(20),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  title: faker.string.alpha(20),
  content: faker.string.alpha(20),
  published: faker.datatype.boolean(),
  authorId: faker.string.alpha(20),
  ...overrideResponse,
});

export const getGetPostResponseMock200 = (overrideResponse: Partial<PostResponse> = {}): PostResponse => ({
  id: faker.string.alpha(20),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  title: faker.string.alpha(20),
  content: faker.string.alpha(20),
  published: faker.datatype.boolean(),
  authorId: faker.string.alpha(20),
  ...overrideResponse,
});

export const getCreatePostMockHandler = (
  overrideResponse?: PostResponce | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostResponce> | PostResponce),
) => {
  return http.post('*/posts', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreatePostResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getCreatePostMockHandler200 = (
  overrideResponse?: PostResponce | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostResponce> | PostResponce),
) => {
  return http.post('*/posts', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreatePostResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetPostsMockHandler = (
  overrideResponse?: PostResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostResponse[]> | PostResponse[]),
) => {
  return http.get('*/posts', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined ? (typeof overrideResponse === 'function' ? await overrideResponse(info) : overrideResponse) : getGetPostsResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetPostsMockHandler200 = (
  overrideResponse?: PostResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostResponse[]> | PostResponse[]),
) => {
  return http.get('*/posts', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPostsResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetUserPostsMockHandler = (
  overrideResponse?: PostResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostResponse[]> | PostResponse[]),
) => {
  return http.get('*/posts/user/:userId', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUserPostsResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetUserPostsMockHandler200 = (
  overrideResponse?: PostResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostResponse[]> | PostResponse[]),
) => {
  return http.get('*/posts/user/:userId', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUserPostsResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetPostMockHandler = (
  overrideResponse?: PostResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostResponse> | PostResponse),
) => {
  return http.get('*/posts/:postId', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined ? (typeof overrideResponse === 'function' ? await overrideResponse(info) : overrideResponse) : getGetPostResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};

export const getGetPostMockHandler200 = (
  overrideResponse?: PostResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PostResponse> | PostResponse),
) => {
  return http.get('*/posts/:postId', async (info) => {
    await delay((() => (process.env.NODE_ENV === 'development' ? 1e3 : 10))());

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPostResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    );
  });
};
export const getPostsMock = () => [getCreatePostMockHandler(), getGetPostsMockHandler(), getGetUserPostsMockHandler(), getGetPostMockHandler()];
