/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePostInput, PostResponce, PostResponse 
} from '../index.schemas';
import { getBaseUrlBasedOnServer } from '@/utils/functions';

/**
 * @summary Create a new post
 */
export type createPostResponse = {
  data: PostResponce;
  status: number;
  headers: Headers;
};

export const getCreatePostUrl = () => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/posts`;
};

export const createPost = async (createPostInput: CreatePostInput, options?: RequestInit): Promise<createPostResponse> => {
  console.log('!!API createPost createPostInput', createPostInput);
  const res = await fetch(getCreatePostUrl(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPostInput),
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createPostResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as createPostResponse;
};

/**
 * @summary Get all posts
 */
export type getPostsResponse = {
  data: PostResponse[];
  status: number;
  headers: Headers;
};

export const getGetPostsUrl = () => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/posts`;
};

export const getPosts = async (options?: RequestInit): Promise<getPostsResponse> => {
  const res = await fetch(getGetPostsUrl(), {
    method: 'GET',
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getPostsResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as getPostsResponse;
};

/**
 * @summary Get all posts of a user
 */
export type getUserPostsResponse = {
  data: PostResponse[];
  status: number;
  headers: Headers;
};

export const getGetUserPostsUrl = (userId: string) => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/posts/user/${userId}`;
};

export const getUserPosts = async (userId: string, options?: RequestInit): Promise<getUserPostsResponse> => {
  const res = await fetch(getGetUserPostsUrl(userId), {
    method: 'GET',
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getUserPostsResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as getUserPostsResponse;
};

/**
 * @summary Get a post by its ID
 */
export type getPostResponse = {
  data: PostResponse;
  status: number;
  headers: Headers;
};

export const getGetPostUrl = (postId: string) => {
  const baseUrl = getBaseUrlBasedOnServer();
  return `${baseUrl}/posts/${postId}`;
};

export const getPost = async (postId: string, options?: RequestInit): Promise<getPostResponse> => {
  const res = await fetch(getGetPostUrl(postId), {
    method: 'GET',
    ...options,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getPostResponse['data'] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as getPostResponse;
};
