/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type { CreatePostInput, PostResponce, PostResponse } from '../index.schemas';
import { customInstance } from '../../mutators/fetch-instance';

/**
 * @summary Create a new post
 */
export type createPostResponse = {
  data: PostResponce;
  status: number;
  headers: Headers;
};

export const getCreatePostUrl = () => {
  return `/posts`;
};

export const createPost = async (createPostInput: CreatePostInput, options?: RequestInit): Promise<createPostResponse> => {
  return customInstance<createPostResponse>(getCreatePostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPostInput),
  });
};

/**
 * @summary Get all posts
 */
export type getPostsResponse = {
  data: PostResponse[];
  status: number;
  headers: Headers;
};

export const getGetPostsUrl = () => {
  return `/posts`;
};

export const getPosts = async (options?: RequestInit): Promise<getPostsResponse> => {
  return customInstance<getPostsResponse>(getGetPostsUrl(), {
    ...options,
    method: 'GET',
  });
};

/**
 * @summary Get all posts of a user
 */
export type getUserPostsResponse = {
  data: PostResponse[];
  status: number;
  headers: Headers;
};

export const getGetUserPostsUrl = (userId: string) => {
  return `/posts/user/${userId}`;
};

export const getUserPosts = async (userId: string, options?: RequestInit): Promise<getUserPostsResponse> => {
  return customInstance<getUserPostsResponse>(getGetUserPostsUrl(userId), {
    ...options,
    method: 'GET',
  });
};

/**
 * @summary Get a post by its ID
 */
export type getPostResponse = {
  data: PostResponse;
  status: number;
  headers: Headers;
};

export const getGetPostUrl = (postId: string) => {
  return `/posts/${postId}`;
};

export const getPost = async (postId: string, options?: RequestInit): Promise<getPostResponse> => {
  return customInstance<getPostResponse>(getGetPostUrl(postId), {
    ...options,
    method: 'GET',
  });
};
